using System.Collections.Generic;

public enum Emotion {
    Joie,
    Confiance,
    Peur,
    Surprise,
    Tristesse,
    Degout,
    Colere,
    Anticipation,
    Extase,
    Amour,
    Culpabilite,
    Plaisir,
    Morbidite,
    Orgueil,
    Optimisme,
    Adoration,
    Soumission,
    Curiosite,
    Sentimentalisme,
    Domination,
    Espoir,
    Terreur,
    Effroi,
    Desespoir,
    Honte,
    Anxiete,
    Etonnement,
    Deception,
    Doute,
    Indignation,
    Chagrin,
    Remords,
    Envie,
    Pessimisme,
    Aversion,
    Mepris,
    Cynisme,
    Rage,
    Aggressivite,
    Vigilance,
    Aucun
}

public static class EmotionCombinator {
    private static readonly Dictionary<(Emotion, Emotion), Emotion> EmotionCombinations = new() {
        { (Emotion.Joie, Emotion.Joie), Emotion.Extase },
        { (Emotion.Joie, Emotion.Confiance), Emotion.Amour },
        { (Emotion.Joie, Emotion.Peur), Emotion.Culpabilite },
        { (Emotion.Joie, Emotion.Surprise), Emotion.Plaisir },
        { (Emotion.Joie, Emotion.Tristesse), Emotion.Aucun },
        { (Emotion.Joie, Emotion.Degout), Emotion.Morbidite },
        { (Emotion.Joie, Emotion.Colere), Emotion.Orgueil },
        { (Emotion.Joie, Emotion.Anticipation), Emotion.Optimisme },
        { (Emotion.Confiance, Emotion.Confiance), Emotion.Adoration },
        { (Emotion.Confiance, Emotion.Peur), Emotion.Soumission },
        { (Emotion.Confiance, Emotion.Surprise), Emotion.Curiosite },
        { (Emotion.Confiance, Emotion.Tristesse), Emotion.Sentimentalisme },
        { (Emotion.Confiance, Emotion.Degout), Emotion.Aucun },
        { (Emotion.Confiance, Emotion.Colere), Emotion.Domination },
        { (Emotion.Confiance, Emotion.Anticipation), Emotion.Espoir },
        { (Emotion.Peur, Emotion.Peur), Emotion.Terreur },
        { (Emotion.Peur, Emotion.Surprise), Emotion.Effroi },
        { (Emotion.Peur, Emotion.Tristesse), Emotion.Desespoir },
        { (Emotion.Peur, Emotion.Degout), Emotion.Honte },
        { (Emotion.Peur, Emotion.Anticipation), Emotion.Anxiete },
        { (Emotion.Surprise, Emotion.Surprise), Emotion.Etonnement },
        { (Emotion.Surprise, Emotion.Tristesse), Emotion.Deception },
        { (Emotion.Surprise, Emotion.Degout), Emotion.Doute },
        { (Emotion.Surprise, Emotion.Colere), Emotion.Indignation },
        { (Emotion.Tristesse, Emotion.Tristesse), Emotion.Chagrin },
        { (Emotion.Tristesse, Emotion.Degout), Emotion.Remords },
        { (Emotion.Tristesse, Emotion.Colere), Emotion.Envie },
        { (Emotion.Tristesse, Emotion.Anticipation), Emotion.Pessimisme },
        { (Emotion.Degout, Emotion.Degout), Emotion.Aversion },
        { (Emotion.Degout, Emotion.Colere), Emotion.Mepris },
        { (Emotion.Degout, Emotion.Anticipation), Emotion.Cynisme },
        { (Emotion.Colere, Emotion.Colere), Emotion.Rage },
        { (Emotion.Colere, Emotion.Anticipation), Emotion.Aggressivite },
        { (Emotion.Anticipation, Emotion.Anticipation), Emotion.Vigilance }
    };

    public static Emotion GetCombinedEmotion(Emotion e1, Emotion e2) {
        var (first, second) = e1 < e2 ? (e1, e2) : (e2, e1);
        return EmotionCombinations.GetValueOrDefault((first, second), Emotion.Aucun);
    }
}